language: scala

scala:
  - 2.11.4

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt ++${TRAVIS_SCALA_VERSION} checkGenerate test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

env:
  global:
    - secure: qeoOx/wOZnap26jlwPgQWxiXPnueijrbk7Op+nPg2utxnFL8L9Ps3udO+eAh4le5oYBxD0C5QqgEcKic+Vfdke+a3grV1IrJNN0gHR8b2y7ODn4fjiumjiwdUPr59d1YRW6O6FeUbOdVAe6uc30RmnX+MBZQSoP8hTlABIleqB0=
    - secure: foA9PR1xb4SNyjyp89QSYXqVaI9NJQhRXLW17kQ2Ei0MkOqNIeRJVopVdXfpX9lH71HIGTxfthpesLfKERRAgpelaMECaPndKdNkHbp42m9DBMpA3FftcuEUCzAChQcD/AEVNignNNx2P28+dE9H6hv9dxPLfYSv9m0pGd0GN+4=
